export const themes = {
  light: {
    name: 'Claro',
    text: '#000',
    textLabel: '#60748A',
    background: '#fff',
    iconBackground: '#F0F2F5',
    transactionTypeDebit: '#FF3B30',
    transactionTypeCredit: '#34C759',
    barStyle: 'dark-content',
    modalBackdrop: 'rgba(0, 0, 0, 0.5)',
    modalBorder: '#CCCCCC',
    accentColor: '#007AFF',
  },
  dark: {
    name: 'Oscuro',
    text: '#fff',
    textLabel: '#60748A',
    background: '#101323',
    iconBackground: '#21284A',
    transactionTypeDebit: '#FF3B30',
    transactionTypeCredit: '#34C759',
    barStyle: 'light-content',
    modalBackdrop: 'rgba(0, 0, 0, 0.7)',
    modalBorder: '#444444',
    accentColor: '#007AFF',
  },
  blue: {
    name: 'Azul',
    text: '#FFFFFF',
    textLabel: '#60748A',
    background: '#007AFF',
    iconBackground: '#F0F2F5',
    transactionTypeDebit: '#FF3B30',
    transactionTypeCredit: '#34C759',
    barStyle: 'light-content',
    modalBackdrop: 'rgba(0, 0, 0, 0.5)',
    modalBorder: '#004C99',
    accentColor: '#FFFFFF',
  },
  green: {
    name: 'Verde',
    text: '#FFFFFF',
    textLabel: '#60748A',
    background: '#34C759',
    iconBackground: '#F0F2F5',
    transactionTypeDebit: '#FF3B30',
    transactionTypeCredit: '#34C759',
    barStyle: 'dark-content',
    modalBackdrop: 'rgba(0, 0, 0, 0.5)',
    modalBorder: '#1E7B38',
    accentColor: '#FFFFFF',
  },
};
