export const themes = {
  light: {
    name: 'Claro',
    text: '#000',
    textLabel: '#60748A',
    background: '#fff',
    iconBackground: '#F0F2F5',
    transactionTypeDebit: 'red',
    transactionTypeCredit: 'green',
  },
  dark: {
    name: 'Oscuro',
    text: '#fff',
    textLabel: '#60748A',
    background: '#101323',
    iconBackground: '#21284A',
    transactionTypeDebit: 'red',
    transactionTypeCredit: 'green',
  },
  blue: {
    name: 'Azul',
    text: '#fff',
    textLabel: '#60748A',
    background: 'blue',
    iconBackground: '#F0F2F5',
    transactionTypeDebit: 'red',
    transactionTypeCredit: 'green',
  },
  green: {
    name: 'Verde',
    text: '#000',
    textLabel: '#60748A',
    background: 'green',
    iconBackground: '#F0F2F5',
    transactionTypeDebit: 'red',
    transactionTypeCredit: 'black',
  },
};
